db_backup/urls.py
from django.urls import path
from . import views

app_name = 'backup'

urlpatterns = [
    path('', views.DatabaseBackupView.as_view(), name='db_backup'),
    path('export/', views.export_database, name='export_database'),
    path('import/', views.import_database, name='import_database'),
]

pixelzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('catalogo/', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('usuarios/', include("users.urls")),
        path('configuration/backup/', include("db_backup.urls")),
    ])),
    path('super/', admin.site.urls),
    path('oauth/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

db_backup/models.py
from django.db import models

# Create your models here.

db_backup/views.py
from django.conf import settings
from django.http import FileResponse
from pathlib import Path
from datetime import datetime
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib import messages
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from authentication.mixins import ValidatePermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


class DatabaseBackupView(LoginRequiredMixin, ValidatePermissionRequiredMixin,  TemplateView):
    template_name = 'db_backup/db_backup.html'
    permission_required = ['private.change_configuration']

@login_required
@permission_required('private.change_configuration', raise_exception=True)
def export_database(request):
    # Ruta del archivo de la base de datos
    database_path = Path(settings.BASE_DIR).joinpath('db.sqlite3')
    
    # Verifica si el archivo existe
    if os.path.exists(database_path):
        # Obtener la fecha y hora actual en el formato deseado
        current_time = datetime.now().strftime('%Y-%m-%d__%H-%M-%S')
        
        # Crear el nombre del archivo de backup con la fecha y hora
        backup_filename = f"backup_{current_time}.sqlite"
        
        # Crear la respuesta con el archivo de backup
        response = FileResponse(open(database_path, 'rb'))
        
        # Establecer el encabezado para la descarga, incluyendo el nombre del archivo con la fecha
        response['Content-Disposition'] = f'attachment; filename="{backup_filename}"'
        
        # Retornar la respuesta de descarga
        return response
    
    # Si la base de datos no existe, usar messages.error para mostrar un error
    messages.error(request, 'Archivo de base de datos no encontrado.')
    
    # Redirigir a la vista de backups
    return redirect('backup:db_backup') 

@login_required
@permission_required('private.change_configuration', raise_exception=True)
def import_database(request):
    if request.method == 'POST' and request.FILES['file']:
        uploaded_file = request.FILES['file']
        file_path = Path(settings.BASE_DIR).joinpath('db.sqlite3')

        # Guarda el archivo subido como la nueva base de datos
        with open(file_path, 'wb') as f:
            for chunk in uploaded_file.chunks():
                f.write(chunk)

        # Mensaje de éxito usando messages.success
        messages.success(request, 'Base de datos importada correctamente.')

        # Redirige a una vista donde el mensaje se pueda mostrar
        return redirect('backup:db_backup')  # Cambia 'home' por la URL de tu página de inicio o vista correspondiente

    # Si no se pudo importar la base de datos, mostrar un mensaje de error
    messages.error(request, 'Error al importar la base de datos.')
    
    # Redirige a la misma página o a una página de error
    return redirect('backup:db_backup') 

db_backup/templates/db_backup/db_backup.html
{% extends 'private/base.html' %}

{% block content %}
<div class="py-5">
    <h1 class="text-center mb-4">Respaldo</h1>

    <div class="row justify-content-center align-items-center text-center">
        <div class="col-lg-5 col-md-6 col-sm-12 mb-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="fw-light mb-3">Importar Base de Datos</h3>
                    <form action="{% url 'backup:import_database' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input class="form-control" type="file" name="file" accept=".sqlite" required>
                        </div>
                        <button class="btn btn-outline-primary w-100" type="submit">Cargar Datos</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-12 col-sm-12 mb-4">
            <p class="h4">o</p>
        </div>

        <div class="col-lg-5 col-md-6 col-sm-12 mb-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="fw-light mb-3">Exportar Base de Datos</h3>
                    <p class="text-muted">Guarda el archivo en un lugar seguro</p>
                    <a class="btn btn-outline-primary w-100" href="{% url 'backup:export_database' %}">Descargar Datos</a>
                </div>
            </div>
        </div>
    </div>
</div>

    

{% endblock %}