pixelzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('catalogo/', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('usuarios/', include("users.urls")),
        path('configuration/backup/', include("db_backup.urls")),
    ])),
    path('super/', admin.site.urls),
    path('oauth/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

private/urls.py
from django.urls import path
from .views import  HomeViewPrivate, EditConfigurationView, ConfigurationView, MyProfileView, EditProfileView, CustomPasswordChangeView, MyUserActionLogView, UserActionLogView

app_name = 'private'

urlpatterns = [
     path('', HomeViewPrivate.as_view(), name='home'),
     path('configuration/', ConfigurationView.as_view(), name='view_configuration'),
     path('configuration/edit/', EditConfigurationView.as_view(), name='update_configuration'),
     path('configuration/actions/', UserActionLogView.as_view(), name = 'view_user_actions'),
     path('profile/', MyProfileView.as_view(), name='view_profile'),
     path('profile/actions/', MyUserActionLogView.as_view(), name = 'view_my_actions'),
     path('profile/edit/', EditProfileView.as_view(), name='update_profile'),
     path('profile/edit/password/', CustomPasswordChangeView.as_view(), name='update_password'),

]

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

private/models.py
from django.db import models
from django.core.cache import cache
from users.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

# Create your models here.
class Configuration(models.Model):
    name = models.CharField(max_length=255, default="Organizacion")
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(
        upload_to='logos/', 
        blank=True, 
        null=True,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]
    )
    banner = models.ImageField(
        upload_to='banners/', 
        blank=True, 
        null=True,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]
    )

    def clean(self):
        if self.logo and self.logo.size > 2 * 1024 * 1024:  # 2 MB
            raise ValidationError("El logo no puede superar los 2 MB.")
        if self.banner and self.banner.size > 5 * 1024 * 1024:  # 5 MB
            raise ValidationError("El banner no puede superar los 5 MB.")
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Configuración"
        verbose_name_plural = "Configuraciones"

    @staticmethod
    def get_configuration():
        configuration = cache.get('configuration')
        if not configuration:
            configuration = Configuration.objects.first()
            if configuration:
                cache.set('configuration', configuration, 60 * 60)  # Caché por 1 hora
        return configuration

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.set('configuration', self, 60 * 60) 

class UserActionLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=255)  # Descripción breve de la acción
    model_name = models.CharField(max_length=100, null=True, blank=True)  # Modelo afectado
    object_id = models.CharField(max_length=100, null=True, blank=True)  # ID del objeto afectado
    timestamp = models.DateTimeField(auto_now_add=True)  # Fecha y hora de la acción
    ip_address = models.GenericIPAddressField(null=True, blank=True)  # IP del usuario
    additional_info = models.JSONField(null=True, blank=True)  # Información extra en formato JSON

    def __str__(self):
        return f"[{self.timestamp}] {self.user} realizó: '{self.action}'"
    
    class Meta:
        indexes = [
        models.Index(fields=['user']),
        models.Index(fields=['timestamp']),
    ]

private/forms.py
from django import forms
from .models import Configuration
from users.models import User
from django.forms.widgets import ClearableFileInput
from django.contrib.auth.password_validation import validate_password

class ConfigurationForm(forms.ModelForm):
    class Meta:
        model = Configuration
        fields = ['name', 'logo', 'description', 'banner']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'logo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'banner': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': 'Nombre de la Organización',
            'logo': 'Logotipo',
            'description': 'Descripción Detallada',
            'banner': 'Banner'
        }

class MyProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'second_last_name', 'phone_number', 'date_of_birth', 'gender', 'photo']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'second_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'email': 'Correo Electrónico',
            'first_name': 'Nombres',
            'last_name': 'Primer apellido',
            'second_last_name': 'Segundo Apellido',
            'phone_number': 'Número de Teléfono',
            'date_of_birth': 'Fecha de Nacimiento',
            'gender': 'Genero',
            'photo': 'Foto de Perfil',
        }


class CustomPasswordChangeForm(forms.Form):
    new_password1 = forms.CharField(
        label="Nueva contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    new_password2 = forms.CharField(
        label="Repetir nueva contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, user=None, **kwargs):
        """
        Permite inicializar el formulario con el usuario actual.
        """
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("new_password1")
        password2 = cleaned_data.get("new_password2")

        if password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        # Validar la seguridad de la contraseña
        validate_password(password1, user=self.user)

        return cleaned_data

    def save(self, commit=True):
        """
        Guarda la nueva contraseña para el usuario.
        """
        self.user.set_password(self.cleaned_data["new_password1"])
        if commit:
            self.user.save()

private/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Configuration, UserActionLog
from .forms import ConfigurationForm, CustomPasswordChangeForm, MyProfileForm
from authentication.mixins import ValidatePermissionRequiredMixin
from django.contrib import messages
from users.models import User
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

from .utils import log_user_action, get_client_ip
# Create your views here.

class HomeViewPrivate(LoginRequiredMixin, TemplateView):
    template_name =  'private/main.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        if user.is_authenticated:
            context['user_permissions'] = user.get_all_permissions()
        else:
            context['user_permissions'] = set()  # Usuario no autenticado
        return context
    
class ConfigurationView(LoginRequiredMixin, TemplateView):
    template_name = 'private/organization/view_organization.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            configuration = Configuration.get_configuration()
        except Configuration.DoesNotExist:
            messages.error(self.request, "La configuración no existe. Contacta al administrador.", extra_tags='error')
            configuration = None
        context['configuration'] = configuration
        return context

class EditConfigurationView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = ['private.change_configuration']
    form_class = ConfigurationForm
    template_name = 'private/organization/update_organization.html'
    success_url = 'private:view_configuration'

    def get_object(self):
        # Asegúrate de que siempre se edite la misma configuración
        return Configuration.get_configuration()
    
    def get_success_url(self):
        if not self.success_url:
            raise ValueError("No se ha configurado 'success_url'.")
        messages.success(self.request, 'Cambios realizados exitosamente.', extra_tags='success')
        return reverse(self.success_url)

    def form_valid(self, form):
        response = super().form_valid(form)  # Procesar la actualización normalmente
        
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la configuración de la organización",
            model_name="Configuration",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        
        return response

class MyProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'private/profile/view_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    
class EditProfileView(LoginRequiredMixin, UpdateView):
    form_class = MyProfileForm
    template_name = 'private/profile/update_profile.html'
    success_url = reverse_lazy('private:view_profile')

    def get_object(self, queryset=None):
        # Retorna el usuario autenticado
        return self.request.user

    def form_valid(self, form):
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la información de su perfil",
            model_name="User",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        messages.success(self.request, 'Usuario actualizado exitosamente.', extra_tags='success')
        return super().form_valid(form)

class BaseUserActionLogView(LoginRequiredMixin, ListView):
    model = UserActionLog
    context_object_name = 'actions'
    ordering = '-timestamp'

class MyUserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/my_action_logs.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)[:15]

class UserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/user_action_log.html'

    def get_queryset(self):
        return super().get_queryset()[:15]
      
class CustomPasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'private/profile/update_password.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('private:view_profile')  # Redirige tras éxito
    success_message = "¡Tu contraseña ha sido cambiada con éxito!"

    def form_valid(self, form):
        # Lógica personalizada antes de guardar la nueva contraseña
        form.save(self.request.user)  # Usa el método save del formulario personalizado
        response = super().form_valid(form)
        print("Contraseña cambiada para el usuario:", self.request.user)
        return response
    

private/templates/private/profile/update_password.html
{% extends "private/base.html" %}
{% load widget_tweaks %}
{% block content %}

<h4>Cambiar Contraseña</h4>


<form method="post">
    {% csrf_token %}
                    <div class="mb-3 position-relative">
                    {{ form.new_password1.label_tag }}
                    <div class="input-group">
                        {{ form.new_password1|add_class:"form-control" }}
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" id="togglePassword1">
                                <i class="bi bi-eye" id="togglePasswordIcon1"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="mb-3 position-relative">
                    {{ form.new_password2.label_tag }}
                    <div class="input-group">
                        {{ form.new_password2|add_class:"form-control" }}
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" id="togglePassword2">
                                <i class="bi bi-eye" id="togglePasswordIcon2"></i>
                            </button>
                        </div>
                    </div>
                </div>
    <a class="btn btn-outline-primary" href="{% url 'private:view_profile' %}">Regresar</a>
    <button class="btn btn-primary" type="submit">Cambiar contraseña</button>
</form>
{% include 'auth/show_password.html' with buttonId="togglePassword1" passwordSelector="[name='new_password1']" iconId="togglePasswordIcon1" %}
{% include 'auth/show_password.html' with buttonId="togglePassword2" passwordSelector="[name='new_password2']" iconId="togglePasswordIcon2" %}

{% endblock %}

private/templates/private/profile/update_profile.html
{% extends 'private/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div>
        <h1>Editando Mi Perfil</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="{{ form.photo.id_for_label }}" class="form-label">Foto</label>
          {{ form.photo|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.email.id_for_label }}" class="form-label">Correo</label>
          {{ form.email|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombres</label>
          {{ form.first_name|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}" class="form-label">Apellido</label>
          {{ form.last_name|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}" class="form-label">Teléfono</label>
          {{ form.phone_number|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.date_of_birth.id_for_label }}" class="form-label">Fecha de Nacimiento</label>
          {{ form.date_of_birth|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.gender.id_for_label }}" class="form-label">Género</label>
          {{ form.gender|add_class:"form-control" }}
      </div>



        <a class="btn btn-outline-primary mt-3" href="{% url 'private:view_profile' %}">Regresar</a>
        <button class="btn btn-primary mt-3" type="submit" >Guardar</button>
      </form>
    </div>
      



{% endblock %}

private/templates/private/profile/view_profile.html
{% extends 'private/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <div class="card position-relative">
        <!-- Imagen de portada -->
        <div class="card-header p-0">
          <div class="bg-dark" style="height: 200px; background-size: cover; background-position: center;"></div>
      </div>
<!-- Menú desplegable en la esquina superior derecha -->
<div class="dropdown position-absolute" style="top: 10px; right: 10px;">
  <button 
      class="btn btn-dark dropdown-toggle" 
      type="button" 
      id="actionMenuButton" 
      data-bs-toggle="dropdown" 
      aria-expanded="false">
      <i class="bi bi-three-dots-vertical"></i>
  </button>

  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="actionMenuButton"> 
    
    <li><a class="dropdown-item" href="{% url 'private:update_profile' %}">
      <i class="bi bi-pencil-square me-2"></i>
      Editar perfil
    </a></li>
    <li><a class="dropdown-item" href="{% url 'private:update_password' %}">
      <i class="bi bi-person-lock me-2"></i>
      Cambiar contraseña
    </a></li>

    <li><a class="dropdown-item" href="{% url 'private:view_my_actions' %}">
      <i class="bi bi-clock-history me-2"></i>
      Historial de cambios
    </a></li>

  </ul>
</div>
        {% include 'users/components/user_card.html' %}
</div>
</div>  
{% endblock content %}