pixelzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('catalogo/', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('usuarios/', include("users.urls")),
        path('configuration/backup/', include("db_backup.urls")),
    ])),
    path('super/', admin.site.urls),
    path('oauth/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
app_name = 'products'

urlpatterns = [
    path('d/', DesignListView.as_view(), name='design_list'),
    path('d/<str:pk>/', DesignDetailView.as_view(), name='design_detail'),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

products/models.py
from django.db import models
import secrets

def generate_random_id():
    return secrets.token_hex(32)

class TShirt(models.Model):
    # Información básica
    fabric = models.CharField(max_length=100, verbose_name="Tela")
    description = models.TextField(blank=True, verbose_name="Descripción")
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio de compra")
    stock = models.PositiveIntegerField(verbose_name="Inventario disponible")
    SIZE_CHOICES = [
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
    ]
    size = models.CharField(max_length=2, choices=SIZE_CHOICES, verbose_name="Talla")

    COLOR_CHOICES = [
        ('white', 'Blanco'),
        ('black', 'Negro'),
        ('red', 'Rojo'),
        ('blue', 'Azul'),
        ('green', 'Verde'),
    ]
    color = models.CharField(max_length=20, choices=COLOR_CHOICES, verbose_name="Color")

    custom_image = models.ImageField(
        upload_to='tshirts/',
        blank=True,
        null=True,
        verbose_name="Imagen"
    )

    # Información técnica
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Última actualización")

    def __str__(self):
        return f'{self.stock or ""}  {self.fabric or ""} {self.color or ""} {self.size or ""}'.strip()

    class Meta:
        verbose_name = "Playera"
        verbose_name_plural = "Playeras"

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Nombre de la etiqueta")

    def __str__(self):
        return self.name
    
class Design(models.Model):
    id = models.CharField(primary_key=True, max_length=64, unique=True, default=generate_random_id)
    image = models.ImageField(
        upload_to='designs/',
        blank=True,
        null=True,
        verbose_name="Diseño"
    )
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio de venta")
    offer_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio de oferta")
    tags = models.ManyToManyField(Tag, blank=True, related_name="tshirts", verbose_name="Categorias")
    description = models.TextField(blank=True, null=True, verbose_name="Descripción")
    on_offer = models.BooleanField(blank=True, null=True, default=False, verbose_name="En Oferta")

products/views.py
from django.shortcuts import render
from .models import Design
from django.views.generic import ListView, DetailView

class DesignListView(ListView):
    model = Design
    template_name = 'products/design/design_list.html'
    context_object_name = 'playeras'

class DesignDetailView(DetailView):
    model = Design
    template_name = 'products/design/design_detail.html'
    context_object_name = 'playera'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_design = self.object  # El diseño actual (detalle)
        
        # Obtener los 3 diseños relacionados por categoría (tags)
        related_designs = Design.objects.filter(
            tags__in=current_design.tags.all()  # Diseños que compartan tags
        ).exclude(id=current_design.id).distinct()[:4]  # Excluir el diseño actual, limitar a 3

        # Agregar los diseños relacionados al contexto
        context['related_designs'] = related_designs
        return context

products/templates/products/design/design_detail.html
{% extends 'public/base.html' %}

{% block content %}
    <!-- Fancybox CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"/>
    <!-- Fancybox JS -->
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>

{% include 'public/frames/navbar.html' %}

<div class="container my-4">
    <div class="row align-items-center">
        <!-- Imagen del producto -->
        <div class="col-12 col-md-6">
            <a 
               data-fancybox="gallery" 
               href="{{ playera.image.url }}" 
               data-caption="{{ playera.description }}">
                <img src="{{ playera.image.url }}" class="img-fluid rounded" alt="{{ playera.description }}">
            </a>
        </div>
        <!-- Información del producto -->
        <div class="col-12 col-md-6">
            <h1>{{ playera.description }}</h1>
            <p class="mt-3">
                {% if playera.on_offer %}
                    <span class="text-primary fw-bold fs-4">Q{{ playera.offer_price }}</span>
                    <span class="text-decoration-line-through text-muted fs-6">Q{{ playera.sale_price }}</span>
                {% else %}
                    <span class="text-primary fw-bold fs-4">Q{{ playera.sale_price }}</span>
                {% endif %}
            </p>
            <p>
                {% for tag in playera.tags.all %}
                    <span class="badge bg-primary text-light">{{ tag.name }}</span>
                {% endfor %}
            </p>
            <!-- Descripción estática -->
            <div class="mt-4">
                <h5>Detalles</h5>
                <ul class="list-group">
                    <li class="list-group-item">Tela<span class="badge text-bg-success rounded-pill ms-2">Algodón</span></li>
                    <li class="list-group-item">Talla<span class="badge text-bg-success rounded-pill ms-2">Cualquiera</span> </li>
                    <li class="list-group-item">Color de playera<span class="badge text-bg-success rounded-pill ms-2">Blanco</span> <span class="badge text-bg-success rounded-pill">Negro</span></li>
                    <li class="list-group-item">Diseño<span class="badge text-bg-success rounded-pill ms-2">Estampado</span> </li>
                    <li class="list-group-item">Personalización<span class="badge text-bg-success rounded-pill ms-2"> Sí</span></li>
                </ul>
            </div>
            <div class="mt-2">
                <div class="alert alert-secondary" role="alert">
                    Puede elegir la(s) talla(s), color de playera(s) y personalizarla (dependiendo el diseño)
                    *Aplican restricciones
                  </div>
            </div>
            <!-- Botón de compra -->
            <div class="mt-4">
                <a href="#" class="btn btn-success w-100">Realizar Pedido 
                    <span class="bi bi-whatsapp"></span>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Configuración de Fancybox -->
<script>
    Fancybox.bind('[data-fancybox="gallery"]', {
        // Configuración personalizada (opcional)
    });
</script>

{% include 'products/design/design_related.html' %}
{% endblock %}

products/templates/products/design/design_list.html
{% extends 'public/base.html' %}

{% block content %}
a
{% endblock %}

products/templates/products/design/design_related.html
<div class="container my-5">
    <h3 class="mb-4">Podrían interesarte</h3>
    <div class="row">
        {% for design in related_designs %}
            <div class="col-12 col-md-4 col-lg-3 mb-4">
                <div class="card h-100" onclick="window.location.href='{% url 'products:design_detail' design.id %}'" style="cursor: pointer;">
                    
                    <img src="{{ design.image.url }}" class="card-img-top" alt="{{ design.description }}">

                    <div class="card-body text-center">
                        <h5 class="card-title">{{ design.description }}</h5>
                        <p class="card-text">
                            {% if design.on_offer %}
                            <span class="text-primary fw-bold fs-4">Q{{ design.offer_price }}</span>
                            <span class="text-decoration-line-through text-muted fs-6">Q{{ design.sale_price }}</span>
                                {% else %}
                                <span class="text-primary fw-bold fs-4">Q{{ design.sale_price }}</span>
                            {% endif %}

                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>