pixelzone/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('catalogo/', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('usuarios/', include("users.urls")),
        path('configuration/backup/', include("db_backup.urls")),
    ])),
    path('super/', admin.site.urls),
    path('oauth/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
from .until import generate_unique_username
from PIL import Image
import secrets

def generate_random_id():
    return secrets.token_hex(32)

class User(AbstractUser):
    ROLE_CHOICES = (
        ('creator', 'Creador'),
        ('admin', 'Administrador'),
    )
    GENDER_CHOICES = (
    ('male', 'Masculino'),
    ('female', 'Femenino'),
    ('prefer_not_to_say', 'Prefiero no decirlo'),
    )
    id = models.CharField(primary_key=True, max_length=64, unique=True, default=generate_random_id)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    second_last_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True, blank=True)

    photo = models.ImageField(upload_to='photos', null=True, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='creator')
    email = models.EmailField(unique=True, null=False, blank=False)
    username = models.CharField(max_length=255, null=True, blank=True)
    
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login_ip = models.GenericIPAddressField(null=True, blank=True)


    USERNAME_FIELD = 'email'  # Usa email como identificador principal
    REQUIRED_FIELDS = ['role', 'username']

    def soft_delete(self):
        self.is_active = False
        self.save()

    def save(self, *args, **kwargs):
        # Generar un username único si no existe
        if not self.username:
            self.username = generate_unique_username(self)
        
        # Llamar al método save del padre para garantizar que la imagen está disponible
        super().save(*args, **kwargs)

        # Procesar la imagen de la foto si está presente
        if self.photo:
            self._resize_image()

        # Asignar permisos específicos según el rol
        self.assign_permissions()

    def _resize_image(self):
        """
        Redimensiona la imagen a un tamaño máximo de 300x300 px si es necesario.
        """
        img_path = self.photo.path
        img = Image.open(img_path)
        max_size = (300, 300)

        if img.height > 300 or img.width > 300:
            img.thumbnail(max_size, Image.LANCZOS)  # Usar Image.LANCZOS directamente
            img.save(img_path)

    def assign_permissions(self):
        """Asigna permisos al usuario según su rol."""
        # Elimina permisos actuales para evitar duplicados
        self.user_permissions.clear()

        # Obtén los permisos según el rol
        if self.role == 'creator':
            permissions = Permission.objects.filter(codename__in=['view_user'])  # Permiso para ver usuarios
        elif self.role == 'admin':
            permissions = Permission.objects.filter(codename__in=['add_user', 'change_user', 'delete_user', 'view_user', 'change_configuration'])  # Permisos de administrador
        else:
            permissions = []

        # Asignar permisos al usuario
        self.user_permissions.add(*permissions)
    
    def get_full_name(self):
        return f'{self.first_name or ""} {self.last_name or ""} {self.second_last_name or ""}'.strip()
    
    def get_MyUser(self):
        MyUser = User.objects.get(email=self.email)
        return MyUser

    def __str__(self):
        return f'{self.get_full_name()} - {self.is_active}'

users/forms.py
from django import forms
from .models import User  

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'phone_number', 'date_of_birth', 'gender', 'photo', 'role']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={
                'type': 'date',  
                'class': 'form-control',  
            }),
        }

users/views.py
from .forms import UserUpdateForm
from .models import User
from authentication.forms import CustomUserCreationForm
from authentication.mixins import ValidatePermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseNotAllowed
from django.utils.timezone import now
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from private.utils import log_user_action, get_client_ip

User = get_user_model()

# Lista de usuarios
class UserListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    permission_required = ['users.view_user']
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'users'
    raise_exception = False
    paginate_by = 10
    order_by = 'username'

    def apply_filters(self, queryset):
        query = self.request.GET.get("q")
        if query:
            filters = (
            Q(username__icontains=query) |
            Q(email__icontains=query) |
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(second_last_name__icontains=query)
        )
            queryset = queryset.filter(filters)
        return queryset.filter(is_active=True)

    def get_queryset(self):
        return self.apply_filters(super().get_queryset())

# Crear usuario
class UserCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    permission_required = ['users.add_user']
    model = User
    form_class = CustomUserCreationForm
    template_name = 'users/user_formCreate.html'
    success_url = reverse_lazy('users:list')
    raise_exception = False

    def form_valid(self, form):
        response = super().form_valid(form)  # Guarda el nuevo usuario
        
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Registró un nuevo usuario",
            model_name="User",
            object_id=str(self.object.id),  # El ID del usuario recién creado
            ip_address=get_client_ip(self.request),
        )
        
        messages.success(self.request, 'Usuario creado exitosamente.', extra_tags='success')
        return response

    def form_invalid(self, form):
        # Mensajes personalizados según el campo con errores
        if 'email' in form.errors:
            for error in form.errors['email']:
                if "already exists" in error:
                    messages.error(self.request, 'El correo ya está registrado.', extra_tags='error')
                elif "inactive" in error:
                    messages.error(self.request, 'El correo está inactivo.', extra_tags='error')
                else:
                    messages.error(self.request, error)

        if 'password2' in form.errors:
            for error in form.errors['password2']:
                if "do not match" in error:
                    messages.error(self.request, 'Las contraseñas no coinciden.', extra_tags='error')
                else:
                    messages.error(self.request, 'Error en la contraseña: ' + error)

        if 'password1' in form.errors:
            for error in form.errors['password1']:
                messages.error(self.request, 'Error en la contraseña: ' + error)

        # Mensaje genérico en caso de otros errores
        if not form.errors:
            messages.error(self.request, 'No fue posible crear el usuario.', extra_tags='error')

        return super().form_invalid(form)

# Editar usuario
class UserUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm  # Cambia 'fields' por 'form_class'
    permission_required = ['users.change_user']
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:list')
    raise_exception = False

    def form_valid(self, form):
        log_user_action(
            user=self.request.user,
            action="Editó la configuración de usuario",
            model_name="User",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        messages.success(self.request, 'Usuario actualizado exitosamente.', extra_tags='success')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('users:view', kwargs={'pk': self.object.id})

@login_required
@permission_required(['users.delete_user', 'users.change_user'], raise_exception=True)
def UserSoftDeleteView(request, pk):
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    usuario = get_object_or_404(User, pk=pk)

    if usuario.is_superuser:
        messages.error(request, 'No puedes eliminar un usuario superadministrador.', extra_tags='error')
        return redirect('users:view', pk=usuario.id)
    
    if usuario == request.user:
        messages.error(request, 'No puedes eliminar tu propio usuario.', extra_tags='error')
        return redirect('users:view', pk=usuario.id)
    
    if usuario.role == 'admin':
        messages.error(request, 'No puedes eliminar un usuario administrador.', extra_tags='error')
        return redirect('users:view', pk=usuario.id)

    usuario.soft_delete()
    log_user_action(
        user=request.user,
        action="Desactivó un usuario",
        model_name="User",
        object_id=str(usuario.id),
        ip_address=get_client_ip(request),
        additional_info={
            "email": usuario.email,
            "username": usuario.username,
            "deleted_at": now().isoformat()  # Registrar cuándo se desactivó
        }
    )
    messages.success(request, f"El usuario {usuario.email} ha sido eliminado correctamente.")
    return redirect('users:list')

class UserDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = User
    permission_required = ['users.view_user']
    template_name = 'users/user_detail.html'
    raise_exception = False
    context_object_name = 'user'

users/templates/users/user_detail.html
{% extends 'private/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <div class="card position-relative">
        <!-- Imagen de portada -->
        <div class="card-header p-0">
            <div class="bg-dark" style="height: 200px; background-size: cover; background-position: center;"></div>     
        </div>
<!-- Menú desplegable en la esquina superior derecha -->
 {% if request.user.role == 'admin' %}
<div class="dropdown position-absolute" style="top: 10px; right: 10px;">
  <button 
      class="btn btn-dark dropdown-toggle" 
      type="button" 
      id="actionMenuButton" 
      data-bs-toggle="dropdown" 
      aria-expanded="false">
      <i class="bi bi-three-dots-vertical"></i>
  </button>

  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="actionMenuButton"> 

    <li><a class="dropdown-item" href="{% url 'users:update' user.pk %}">
        <i class="bi bi-pencil-square me-2"></i>
        Editar perfil
    </a></li>
    <li>
        <form action="{% url 'users:desactivar' user.pk %}" method="POST" style="display:inline;" id="deleteForm{{ user.pk }}">
            {% csrf_token %}
            <a 
              href="#" 
              class="dropdown-item" 
              onclick="confirmDelete(event, {{ user.pk }})"
            >
              <i class="bi bi-trash3 me-2"></i>
              Eliminar perfil
            </a>
        </form>
      </li>
    
  </ul>
</div>
{% endif %}
        {% include 'users/components/user_card.html' %}
        <div class="d-flex justify-content-center mb-4">
            <a class="btn btn-primary" href="{% url 'users:list' %}">
                <i class="bi bi-arrow-left me-2"></i>
                Regresar</a>
        </div>
    </div>
</div>

<script>
    function confirmDelete(event, userId) {
  event.preventDefault(); // Evitar que el enlace se ejecute
  const deleteForm = document.getElementById(`deleteForm${userId}`);

  if (!deleteForm) {
    console.error("Formulario no encontrado para el usuario con ID:", userId);
    return;
  }

  Swal.fire({
    title: "¿Estás seguro?",
    text: "¡No podrás revertir esto!",
    icon: "warning",
    showCancelButton: true,
    confirmButtonColor: "#d33",
    cancelButtonColor: "#3085d6",
    confirmButtonText: "Sí, eliminar",
    cancelButtonText: "Cancelar"
  }).then((result) => {
    if (result.isConfirmed) {
      deleteForm.submit(); // Enviar el formulario
    }
  });
}

  </script>
{% endblock %}

users/templates/users/user_form.html
{% extends "private/base.html" %}
{% load widget_tweaks %}

{% block content %}
        <h1>Editando Usuario</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.photo.id_for_label }}" class="form-label">Foto</label>
                {{ form.photo|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                {{ form.username|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.email.id_for_label }}" class="form-label">Correo</label>
                {{ form.email|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombres</label>
                {{ form.first_name|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Apellido</label>
                {{ form.last_name|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.phone_number.id_for_label }}" class="form-label">Teléfono</label>
                {{ form.phone_number|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.date_of_birth.id_for_label }}" class="form-label">Fecha de Nacimiento</label>
                {{ form.date_of_birth|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.gender.id_for_label }}" class="form-label">Género</label>
                {{ form.gender|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.role.id_for_label }}" class="form-label">Rol</label>
                {{ form.role|add_class:"form-control" }}
            </div>

            <a class="btn btn-outline-primary mt-3" href="{% url 'users:list' %}">Cancelar</a>
            <button class="btn btn-primary mt-3" type="submit">Guardar</button>
        </form>
{% endblock %}

users/templates/users/user_formCreate.html
{% extends "private/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <div>
        <h1>{{ view.object.pk|yesno:"Editar Usuario,Crear Usuario" }}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombres</label>
                {{ form.first_name|add_class:"form-control" }}
            </div>
            <div class="row">

                <div class="col form-group">
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Primer Apellido</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="col">
                    <label for="{{ form.second_last_name.id_for_label }}" class="form-label">Segundo Apellido</label>
                {{ form.second_last_name|add_class:"form-control" }}
            </div>

            </div>
            

            <div class="form-group">
                <label for="{{ form.email.id_for_label }}" class="form-label">Correo Electr&oacute;nico</label>
                {{ form.email|add_class:"form-control" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.phone_number.id_for_label }}" class="form-label">Teléfono</label>
                {{ form.phone_number|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.date_of_birth.id_for_label }}" class="form-label">Fecha de Nacimiento</label>
                {{ form.date_of_birth|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="{{ form.gender.id_for_label }}" class="form-label">Género</label>
                {{ form.gender|add_class:"form-control" }}
            </div>
            
            <div class="mb-3 position-relative">
                {{ form.password1.label_tag }}
                <div class="input-group">
                    {{ form.password1|add_class:"form-control" }}
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-secondary" id="togglePassword1">
                            <i class="bi bi-eye" id="togglePasswordIcon1"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="mb-3 position-relative">
                {{ form.password2.label_tag }}
                <div class="input-group">
                    {{ form.password2|add_class:"form-control" }}
                    <div class="input-group-append">
                        <button type="button" class="btn btn-outline-secondary" id="togglePassword2">
                            <i class="bi bi-eye" id="togglePasswordIcon2"></i>
                        </button>
                    </div>
                </div>
            </div>

            <a class="btn btn-outline-primary mt-3" href="{% url 'users:list' %}">Cancelar</a>
            <button class="btn btn-primary mt-3" type="submit">Guardar</button>
        </form>
    </div>

    {% include 'auth/show_password.html' with buttonId="togglePassword1" passwordSelector="[name='password1']" iconId="togglePasswordIcon1" %}
    {% include 'auth/show_password.html' with buttonId="togglePassword2" passwordSelector="[name='password2']" iconId="togglePasswordIcon2" %}
{% endblock %}

users/templates/users/user_list.html
{% extends "private/base.html" %}
{% block content %}

<h1 class="mb-4 text-center">Usuarios</h1>
<div class="d-flex justify-content-between align-items-center mb-4">
    {% if request.user.role == 'admin' %}
    <a class="btn btn-primary" href="{% url 'users:create' %}">
        <i class="bi bi-person-plus"></i> Crear Usuario
    </a>
    {% else %}
    <a class="btn btn-outline-primary disabled" href=".">
        <i class="bi bi-person-plus"></i> Crear Usuario
    </a>
    {% endif %}
    <form method="get" class="d-flex w-50">
        <div class="input-group">
            <input 
                type="text" 
                name="q" 
                class="form-control" 
                placeholder="Buscar usuario..." 
                value="{{ request.GET.q }}">
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-search "></i>
            </button>
        </div>
    </form>
</div>

        {% include 'users/user_pagination.html' %}
        <div class="container-fluid py-4">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>Usuario</th>
                            <th>Correo</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Rol</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr onclick="window.location.href='{% url 'users:view' user.id %}'" style="cursor: pointer;">
                            <td>{{ user.username|default:"--" }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <!-- <td>{{ user.last_login|date:"d M Y, H:i" }}</td> -->
                            <td>
                                {% if user.role == 'admin' %}
                                <span class="badge bg-success">{{ user.get_role_display }}</span>
                                {% else %}
                                <span class="badge bg-primary">{{ user.get_role_display }}</span>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
       
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
                tooltipTriggerList.map(function (tooltipTriggerEl) {
                    return new bootstrap.Tooltip(tooltipTriggerEl);
                });
            });
        </script>
{% endblock %}

users/templates/users/user_pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination pagination-sm justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?q={{ request.GET.q }}&page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">&lsaquo;</span>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if num == 1 or num == page_obj.paginator.num_pages or num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
        <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?q={{ request.GET.q }}&page={{ num }}">{{ num }}</a>
        </li>
        {% elif num == page_obj.number|add:-3 or num == page_obj.number|add:3 %}
        <li class="page-item disabled">
            <span class="page-link">...</span>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?q={{ request.GET.q }}&page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&rsaquo;</span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
        </li>
        {% endif %}
    </ul>
</nav>